Provide filter on dynamic table
nicwb/cts pull request #235
Opened 2024-12-04 11:18 UTC by kirito-roy

> [!IMPORTANT]
> PR for [Task-315: Provide filter on dynamic table](https://tree.taiga.io/project/santosh84das-ifms-pension-module/task/315)

## The guidelines are followed when sending PR

- [ ] PR has a single commit only.
- [ ] Commit Message is same as the task title.
- [ ] Commit doesn't contain any console log statement.
- [ ] Files added/changed are actually required for this task.
- [ ] This task contains routing and breadcrumbs has been added.
- [ ] This task adds new component with deep-link support implemented.

2024-12-05 02:25 UTC, abusalam requested changes
Update Version number

2024-12-05 12:05 UTC, amit12345678901 approved these changes

2024-12-06 08:20 UTC, abusalam approved these changes

2024-12-06 09:11 UTC, abusalam approved these changes

2024-12-06 09:11 UTC, merged